### ISSUE TITLE
Github action naming configuration

### ISSUE THREAD

**Issue by Tansito** [Qiskit/gh-actions#16]
In https://github.com/Qiskit/qiskit.org/pull/2424 we were discussing about what naming should we setup in the different github action to make the action clear. Some interesting proposals came to light:

- `Preview / set-up / code-engine` and `Preview / tear-down / code-engine`
- `Preview / set-up / deploy` and `Preview / tear-down / clean-up`
- `Preview / code-engine / deploy` and `Preview / code-engine / cleanup`
- `Preview / deploy / code-engine` and `Preview / cleanup / code-engine`

The current configuration is the third one. In my absolutely subjective point of view I liked the idea than `code-engine` doesn't appear so I would go for the second one. Any comments @vabarbosa @abdonrd ?

**Comment by abdonrd** [comment]
I don't have a strong opinion; option two that you propose is fine too!

Just maybe `setup` vs `set-up` and `teardown` vs `tear-down`?
- `Preview / setup / deploy` and `Preview / teardown / cleanup`

https://www.google.com/search?q=setup+or+set+up
https://www.google.com/search?q=teardown+or+tear+down

**Comment by Tansito** [comment]
Here I have 100% confident on Va's english so he decides 😂

**Comment by abdonrd** [comment]
It's also true! haha
I have asked because I don't know the most correct way!

**Comment by vabarbosa** [comment]
i would agree that we don't include `code-engine` in the naming. i also would vote for the second options.

i dont know about my English (i definitely dont trust it), but my understanding is that `setup` is a noun while `set up` would be the verb. the decision then comes down to whether we want the name be in the form of a doing an action (`set-up`) or not (`setup`).

**Comment by vabarbosa** [comment]
revisiting this because one issue i see with naming both workflows `Preview` is that when you look at the Actions tab, you see two `Preview` workflows.

unfortunately, this causes some confusion as to which one is the clean up preview and which is one is the deploy preview.

<img src="https://user-images.githubusercontent.com/13156555/150860080-15f7582b-a7c4-41fd-a366-14a0b4546f80.png" width=400>

what are your thoughts on maybe one of these:

- `Preview Deploy / setup / deploy`  or  `Preview (deploy) / setup / deploy`
- `Preview Clean / teardown / clean`  or  `Preview (clean) / teardown / clean`

or another suggestions you have?

**Comment by Tansito** [comment]
You are totally right. By now I couldn't think in another better approach than:
- `Preview (deploy) / setup / deploy`
- `Preview (clean) / teardown / clean`
I liked that one.

**Comment by abdonrd** [comment]
I'm ok with that!

**Comment by vabarbosa** [comment]
all workflows updated accordingly. thanks.
